@startuml model
left to right direction
skinparam dpi 300

(Salary) #LightBlue

(Programming Languages) #LightBlue


(Developer Type) #LightGreen

(Education) #LightGreen

(Employment)

(Years Working) #LightGreen

(Years Coding)

(Years Professionally Coding)

(Programming Languages) --> (Salary)


(Education) --> (Salary)
(Education) --> (Years Coding)
(Education) --> (Programming Languages)


(Developer Type) --> (Programming Languages)
(Developer Type) --> (Salary)


(Employment) --> (Salary)


(Years Working) --> (Salary)

(Years Coding) --> (Programming Languages)

(Employment) --> (Developer Type)

(Years Working) --> (Years Professionally Coding)

(Years Professionally Coding) --> (Years Coding)


' (Programming Languages) --> (Salary)

' (Developer Type) --> (Programming Languages)

' (Developer Type) --> (Salary)

' (Education Level) --> (Developer Type)
' (Education Level) --> (Programming Experience)

' (Work Experience) --> (Salary)

' (Work Experience) --> (Professional Programming Experience)
' (Professional Programming Experience) -> (Programming Experience)

' (Programming Experience) --> (Programming Languages)


' (Employment Status) --> (Salary)

@enduml
